services:

    Analogic\AlertBundle\EventListener\ExceptionListener:
        arguments:
          - "%analogic_alert.enabled%"
          - '@Analogic\AlertBundle\Alerter\Alerter'
          - "%analogic_alert.ignore%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            - { name: kernel.event_listener, event: console.exception }

    Analogic\AlertBundle\Alerter\Alerter:
        arguments:
          - "@mailer"
          - "@templating"
          - "@logger"
          - "%analogic_alert.from%"
          - "%analogic_alert.to%"
          - "%analogic_alert.prefix%"

    Analogic\AlertBundle\Controller\ErrorController:
        arguments:
          - '@Analogic\AlertBundle\Alerter\Alerter'
          - "%analogic_alert.javascript_ignore_regex%"

    Analogic\AlertBundle\Twig\Helper:
        public: false
        arguments:
          - "%analogic_alert.enabled%"
          - "@router"
        tags:
            - { name: twig.extension }